local M = {}

function M.setup(opts)
  local c = require('neology.colors').setup(opts)

  local highlights = {
    Normal                    = { bg = c.bg, fg = c.norm },
    Cursor                    = { bg = c.light_black, fg = c.norm },
    Comment                   = { fg = c.bg_subtle, gui = 'italic' },
    Constant                  = { fg = c.norm_subtle },
    Character                 = { link = 'Constant' },
    Number                    = { link = 'Constant' },
    Boolean                   = { link = 'Constant' },
    Float                     = { link = 'Constant' },
    String                    = { link = 'Constant' },
    Identifier                = { fg = c.fg, gui = 'italic' },
    Function                  = { link = 'Identifier' },
    Statement                 = { fg = c.norm, gui = 'bold' },
    Conditonal                = { link = 'Statement' },
    Repeat                    = { link = 'Statement' },
    Label                     = { link = 'Statement' },
    Keyword                   = { link = 'Statement' },
    Exception                 = { link = 'Statement' },
    Operator                  = { fg = c.norm, gui = 'bold' },
    PreProc                   = { fg = c.norm_subtle },
    Include                   = { link = 'PreProc' },
    Define                    = { link = 'PreProc' },
    Macro                     = { link = 'PreProc' },
    PreCondit                 = { link = 'PreProc' },
    Type                      = { fg = c.norm },
    StorageClass              = { link = 'Type' },
    Structure                 = { link = 'Type' },
    Typedef                   = { link = 'Type' },
    Special                   = { fg = c.norm_subtle, gui = 'italic' },
    SpecialChar               = { link = 'Special' },
    Tag                       = { link = 'Special' },
    Delimiter                 = { link = 'Special' },
    SpecialComment            = { link = 'Special' },
    Debug                     = { link = 'Special' },
    Underlined                = { fg = c.norm, gui = 'underline' },
    Ignore                    = { fg = c.bg },
    Error                     = { fg = c.white, bg = c.red },
    Todo                      = { fg = c.pink, gui = 'underline' },
    SpecialKey                = { fg = c.green },
    NonText                   = { fg = c.medium_gray },
    Directory                 = { fg = c.norm, gui = 'bold' },
    ErrorMsg                  = { fg = c.red },
    IncSearch                 = { bg = c.norm_subtle, fg = c.bg },
    Search                    = { bg = c.norm, fg = c.bg, gui = 'bold' },
    MoreMsg                   = { fg = c.medium_gray, gui = 'bold' },
    ModeMsg                   = { link = 'MoreMsg' },
    LineNr                    = { fg = c.bg_med_subtle },
    CursorLineNr              = { fg = c.bg_subtle, gui = 'bold' },
    Question                  = { fg = c.red },
    StatusLine                = { bg = c.bg_very_very_subtle, fg = c.norm_subtle },
    StatusLineNC              = { bg = c.bg_very_very_subtle, fg = c.bg_med_subtle },
    WinBar                    = { link = 'StatusLine' },
    WinBarNC                  = { link = 'StatusLineNC' },
    VertSplit                 = { bg = c.bg_very_very_subtle, fg = c.bg_very_very_subtle },
    Title                     = { fg = c.light_gray },
    Visual                    = { fg = c.norm, bg = c.bg_very_subtle },
    VisualNOS                 = { bg = c.bg_mid_subtle },
    WarningMsg                = { fg = c.yellow },
    WildMenu                  = { fg = c.bg, bg = c.norm },
    Folded                    = { fg = c.medium_gray },
    FoldColumn                = { fg = c.bg_subtle },
    DiffAdd                   = { fg = c.green },
    DiffDelete                = { fg = c.red },
    DiffChange                = { fg = c.yellow },
    DiffText                  = { fg = c.blue },
    SignColumn                = { fg = c.green },
    SpellBad                  = { gui = 'undercurl', sp = c.red },
    SpellCap                  = { gui = 'undercurl', sp = c.green },
    SpellRare                 = { gui = 'undercurl', sp = c.orange },
    SpellLocal                = { gui = 'undercurl', sp = c.green },
    Pmenu                     = { fg = c.norm, bg = c.bg_very_subtle },
    PmenuSel                  = { fg = c.fg, bg = c.pink },
    PmenuSbar                 = { fg = c.norm, bg = c.bg_mid_subtle },
    PmenuThumb                = { fg = c.norm, bg = c.bg_mid_subtle },
    TabLine                   = { fg = c.norm, bg = c.bg_very_very_subtle },
    TabLineSel                = { fg = c.fg, bg = c.pink, gui = 'bold' },
    TabLineFill               = { fg = c.norm, bg = c.bg_very_very_subtle },
    CursorColumn              = { bg = c.bg_very_very_subtle },
    CursorLine                = { bg = c.bg_very_very_subtle },
    ColorColumn               = { bg = c.bg_mid_subtle },
    MatchParen                = { bg = c.bg_subtle, fg = c.norm },
    qfLineNr                  = { fg = c.medium_gray },
    -- LSP diagnostics
    DiagnosticUnderlineError  = { gui = 'undercurl', sp = c.red },
    DiagnosticUnderlineWarn   = { gui = 'undercurl', sp = c.orange },
    DiagnosticUnderlineInfo   = { gui = 'undercurl', sp = c.green },
    DiagnosticUnderlineHint   = { gui = 'undercurl', sp = c.green },
    -- Syntastic
    SyntasticWarningSign      = { fg = c.yellow },
    SyntasticWarning          = { bg = c.yellow, fg = c.black, gui = 'bold' },
    SyntasticErrorSign        = { fg = c.red },
    SyntasticError            = { bg = c.red, fg = c.white, gui = 'bold' },
    -- which-key.nvim
    WhichKey                  = { bg = c.bg, fg = c.pink, gui = 'bold' },
    WhichKeyDesc              = { bg = c.bg, fg = c.norm_subtle, gui = 'bold' },
    WhichKeySeparator         = { bg = c.bg, fg = c.norm, gui = 'bold' },
    WhichKeyFloat             = { bg = c.bg },
    WhichKeyGroup             = { link = 'WhichKey' },
    -- Neomake
    NeomakeWarningSign        = { link = 'SyntasticWarningSign' },
    NeomakeErrorSign          = { link = 'SyntasticErrorSign' },
    -- ALE
    ALEWarningSign            = { link = 'SyntasticWarningSign' },
    ALEErrorSign              = { link = 'SyntasticErrorSign' },
    -- Signify, git-gutter
    SignifySignAdd            = { fg = c.norm_subtle },
    SignifySignDelete         = { link = 'SignifySignAdd' },
    SignifySignChange         = { link = 'SignifySignAdd' },
    GitGutterAdd              = { link = 'SignifySignAdd' },
    GitGutterDelete           = { link = 'SignifySignAdd' },
    GitGutterChange           = { link = 'SignifySignAdd' },
    GitGutterChangeDelete     = { link = 'SignifySignAdd' },
    -- Markdown
    markdownCode              = { fg = c.bg_subtle },
    markdownLinkReference     = { fg = c.bg_subtle },
    markdownJekyllFrontMatter = { fg = c.bg_subtle },
    markdownCodeBlock         = { fg = c.norm },
    markdownCodeDelimiter     = { fg = c.norm },
    markdownHeadingDelimiter  = { fg = c.fg },
    markdownRule              = { fg = c.bg_subtle },
    markdownHeadingRule       = { fg = c.bg_subtle },
    htmlH1                    = { fg = c.fg, bg = c.bg, gui = 'bold' },
    htmlH2                    = { fg = c.fg, bg = c.bg, gui = 'bold' },
    htmlH3                    = { fg = c.fg, bg = c.bg, gui = 'bold' },
    htmlH4                    = { fg = c.fg, bg = c.bg, gui = 'bold' },
    htmlH5                    = { fg = c.fg, bg = c.bg, gui = 'bold' },
    htmlH6                    = { fg = c.fg, bg = c.bg, gui = 'bold' },
    mkdDelimiter              = { fg = c.fg },
    markdownId                = { fg = c.light_gray },
    markdownBlockquote        = { fg = c.bg_subtle },
    markdownItalic            = { fg = c.light_gray, gui = 'italic' },
    mkdBold                   = { fg = c.fg, gui = 'bold' },
    mkdInlineURL              = { fg = c.fg, gui = 'italic' },
    mkdListItem               = { fg = c.fg },
    markdownOrderedListMarker = { fg = c.fg },
    mkdlink                   = { fg = c.fg, gui = 'bold' },
    markdownLinkDelimiter     = { fg = c.fg },
    mkdURL                    = { fg = c.norm_subtle, gui = 'italic' },
    -- fidget.nvim
    FidgetTask                = { fg = c.bg_very_very_subtle },
    FidgetTitle               = { fg = c.bg_very_very_subtle },
    -- tree-sitter
    ["@text.title"]           = { fg = c.text, gui = 'bold' },
  }

  if opts and opts.highlights then
    highlights = vim.tbl_deep_extend('force', highlights, opts.highlights)
  end

  return highlights
end

return M
